spring.application.name=wildlife-backend

# MongoDB
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/wildlife_library}
spring.data.mongodb.database=${MONGODB_DATABASE:wildlife_library}

# Swagger / OpenAPI endpoints
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
